//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conspiracao.Domain.Models
{
    using Conspiracao.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateOrcamentoItem")]
    public partial class TemplateOrcamentoItem : KeyAuditableEntity
    {
        public TemplateOrcamentoItem()
        {
        }

        [Required]
        public string Codigo { get; set; }

        [Required]
        public string Nome { get; set; }
        
        public string Formula { get; set; }

        [ForeignKey("ItemPlanoContas")]
        public long? IdItemPlanoContas { get; set; }
        public ItemPlanoContas ItemPlanoContas { get; set; }

        [ForeignKey("TemplateOrcamentoGrupo")]
        public long IdTemplateOrcamentoGrupo { get; set; }
        public TemplateOrcamentoGrupo TemplateOrcamentoGrupo { get; set; }        
    }
}
