//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

    [Table("Template")]
    public partial class Template : KeyAuditableEntity
    {
        public Template()
        {
            this.TemplateGrupos = new HashSet<TemplateGrupo>();
            this.Orcamentos = new HashSet<ProjetoOrcamento>();
        }

        [Required]
        public string Nome { get; set; }

        public bool IndAtivo { get; set; }

        //public TipoTemplateEnum TipoTemplate { get; set; }
        [ForeignKey("TipoTemplate")]
        public long IdTipoTemplate { get; set; }
        public virtual ConteudoTabelaDominio TipoTemplate { get; set; }


        [ForeignKey("Nucleo")]
        public long IdNucleo { get; set; }
        public virtual Nucleo Nucleo { get; set; }

        [ForeignKey("TipoProjeto")]
        public long? IdTipoProjeto { get; set; }
        public virtual ConteudoTabelaDominio TipoProjeto { get; set; }

        public virtual ICollection<TemplateGrupo> TemplateGrupos { get; set; }        
        public virtual ICollection<ProjetoOrcamento> Orcamentos { get; set; }       
    }
}
