//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conspiracao.Domain.Models
{
    using Conspiracao.Framework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateAICPItem")]
    public partial class TemplateAICPItem : Entity
    {
        public TemplateAICPItem()
        {
        }

        public string Codigo { get; set; }
        public string Nome { get; set; }
        public bool IndAtivo { get; set; }

        [ForeignKey("ModeloAICP")]
        public long IdModeloAICP { get; set; }
        public ModeloAICP ModeloAICP { get; set; }

        [ForeignKey("TemplateAICPGrupo")]
        public long IdTemplateAICPGrupo { get; set; }
        public TemplateAICPGrupo TemplateAICPGrupo { get; set; }        
    }
}
