//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateItem")]
    public partial class TemplateItem : KeyAuditableEntity
    {
        public TemplateItem()
        {
        }

        //[Required]
        public string Codigo { get; set; }

        [Required]
        public string Nome { get; set; }
        
        public string Formula { get; set; }

        [ForeignKey("ItemPlanoContas")]
        public long? IdItemPlanoContas { get; set; }
        public ItemPlanoContas ItemPlanoContas { get; set; }

        [ForeignKey("TemplateGrupo")]
        public long IdTemplateGrupo { get; set; }
        public TemplateGrupo TemplateGrupo { get; set; }
        
        public bool IndAtivo { get; set; }

        [ForeignKey("ModeloAICP")]
        public long? IdModeloAICP { get; set; }
        public ModeloAICP ModeloAICP { get; set; }
    }
}
