//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conspiracao.Domain.Models
{
    using Conspiracao.Framework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateOrcamentoGrupo")]
    public partial class TemplateOrcamentoGrupo : KeyAuditableEntity
    {
        public TemplateOrcamentoGrupo()
        {
            this.TemplateOrcamentoItems = new HashSet<TemplateOrcamentoItem>();
        }

        [Required]
        public string Codigo { get; set; }

        [Required]
        public string Nome { get; set; }
        
        [ForeignKey("TemplateOrcamento")]
        public long IdTemplateOrcamento { get; set; }
        public TemplateOrcamento TemplateOrcamento { get; set; }

        public virtual ICollection<TemplateOrcamentoItem> TemplateOrcamentoItems { get; set; }
    }
}
