//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conspiracao.Domain.Models
{
    using Conspiracao.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateOrcamento")]
    public partial class TemplateOrcamento : KeyAuditableEntity
    {
        public TemplateOrcamento()
        {
            this.TemplateOrcamentoGrupos = new HashSet<TemplateOrcamentoGrupo>();
            this.Orcamentos = new HashSet<ProjetoOrcamento>();
        }

        [Required]
        public string Nome { get; set; }

        public bool IndAtivo { get; set; }
        
        [ForeignKey("Nucleo")]
        public long IdNucleo { get; set; }
        public virtual Nucleo Nucleo { get; set; }

        [ForeignKey("TipoProjeto")]
        public long? IdTipoProjeto { get; set; }
        public virtual ConteudoTabelaDominio TipoProjeto { get; set; }

        public virtual ICollection<TemplateOrcamentoGrupo> TemplateOrcamentoGrupos { get; set; }
        public virtual ICollection<ProjetoOrcamento> Orcamentos { get; set; }
    }
}
