//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conspiracao.Domain.Models
{
    using Conspiracao.Framework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateAICPGrupo")]
    public partial class TemplateAICPGrupo : Entity
    {
        public TemplateAICPGrupo()
        {
            this.TemplateAICPItems = new HashSet<TemplateAICPItem>();
        }

        public string Codigo { get; set; }
        public string Nome { get; set; }
        public bool IndAtivo { get; set; }

        [ForeignKey("TemplateAICP")]
        public long IdTemplateAICP { get; set; }
        public TemplateAICP TemplateAICP { get; set; }
        
        public virtual ICollection<TemplateAICPItem> TemplateAICPItems { get; set; }
    }
}
