//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conspiracao.Domain.Models
{
    using Conspiracao.Framework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TemplateAICP")]
    public partial class TemplateAICP : Entity
    {
        public TemplateAICP()
        {
            this.TemplateAICPGrupos = new HashSet<TemplateAICPGrupo>();
        }

        public string Nome { get; set; }
        public bool IndAtivo { get; set; }
        
        [ForeignKey("Nucleo")]
        public long IdNucleo { get; set; }
        public Nucleo Nucleo { get; set; }

        public virtual ICollection<TemplateAICPGrupo> TemplateAICPGrupos { get; set; }
    }
}
