//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Agnus.Domain.Models;
namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CategoriaPremio")]
    public partial class CategoriaPremio : KeyAuditableEntity
    {
        public CategoriaPremio()
        {
            this.ProjetoPremio = new HashSet<ProjetoPremio>();
        }

        [Index("IX_Codigo_IX", IsUnique = true)]
        public long Codigo { get; set; }
        //public long Id { get; set; }
        //public string IdCategoriaPremio { get; set; }
        public string TxtCategoriaPremio { get; set; }
        public bool IndAtivo { get; set; }

        [ForeignKey("TipoPremio")]
        public long IdTipoPremio { get; set; }
        public virtual TipoPremio TipoPremio { get; set; }

        public virtual ICollection<ProjetoPremio> ProjetoPremio { get; set; }
    }
}
