//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("IncentivoFiscal")]
    public partial class IncentivoFiscal : KeyAuditableEntity
    {
        public IncentivoFiscal()
        {
            this.ProjetoCaptacao = new HashSet<ProjetoCaptacao>();
        }
    
        //public long Id { get; set; }
        [Index("IX_Codigo_IX", IsUnique = true)]
        public long Codigo { get; set; }
        public string TxtLeiIncentivo { get; set; }
        public string TxtArtigo { get; set; }
        public bool IndAtivo { get; set; }
        //public long? IdIncentivoFiscal { get; set; }

        [ForeignKey("PessoaOrgaoConcessor")]
        public long IdPessoaOrgaoConcessor { get; set; }
        public virtual Pessoa PessoaOrgaoConcessor { get; set; }

        public virtual ICollection<ProjetoCaptacao> ProjetoCaptacao { get; set; }
    }
}
