//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using Agnus.Domain.Models;
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using Agnus.Domain.Models.Enum;

    [Table("PedidoCompra")]
    public partial class PedidoCompra : KeyAuditableEntity
    {
        public PedidoCompra()
        {
            this.PedidoCompras = new HashSet<PedidoCompra>();
            this.PedidoCompraItem = new HashSet<PedidoCompraItem>();
            this.Arquivos = new HashSet<Arquivo>();
        }

        [DataMember]
        public long CodPedido { get; set; }

        [DataMember]
        public string LoginSolicitante { get; set; }

        [DataMember]
        public DateTime DataPedidoCompra { get; set; }

        [DataMember]
        public int CodStatusPedidoCompra { get; set; }

        [DataMember]
        public DateTime DatStatusPedidoCompra { get; set; }

        [DataMember]
        public string TxtJustificativa { get; set; }

        [ForeignKey("Empresa")]
        public long IdEmpresa { get; set; }
        public virtual Empresa Empresa { get; set; }

        [ForeignKey("StatusPedidoCompra")]
        [DataMember]
        public long IdStatusPedidoCompra { get; set; }
        public virtual ConteudoTabelaDominio StatusPedidoCompra { get; set; }

        [ForeignKey("TipoPedidoCompra")]
        [DataMember]
        public long? IdTipoPedidoCompra { get; set; }

        [DataMember]
        public virtual ConteudoTabelaDominio TipoPedidoCompra { get; set; }

        [ForeignKey("PedidoCompra1")]
        [DataMember]
        public long? IdPedidoCompraOriginal { get; set; }
        public virtual PedidoCompra PedidoCompra1 { get; set; }

        [ForeignKey("Nucleo")]
        [DataMember]
        public long IdNucleo { get; set; }
        public virtual Nucleo Nucleo { get; set; }

        [ForeignKey("Projeto")]
        [DataMember]
        public long? IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        [ForeignKey("CentroCusto")]
        [DataMember]
        public long? IdCentroCusto { get; set; }
        public virtual CentroCusto CentroCusto { get; set; }

        public virtual ICollection<PedidoCompra> PedidoCompras { get; set; }
        public virtual ICollection<PedidoCompraItem> PedidoCompraItem { get; set; }

        public virtual ICollection<Arquivo> Arquivos { get; set; }
        //[ForeignKey("Arquivo")]
        //public long? IdArquivo { get; set; }
        //public virtual Arquivo Arquivo { get; set; }

        public decimal CalcularSubTotal()
        {
            return this.PedidoCompraItem.Where(x => x.StatusItemPedidoCompra.Codigo != (int)StatusItemPedidoCompraEnum.Cancelado).Sum(x => x.QtdPedidoCompra * x.ValorUnitario);
        }

        public decimal CalcularDesconto()
        {
            return this.PedidoCompraItem.Sum(x => x.Desconto);
        }

        public decimal CalcularValorTotal()
        {
            return CalcularSubTotal() - CalcularDesconto();
        }
    }
}
