//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoHistoricoStatus")]
    public partial class ProjetoHistoricoStatus : KeyAuditableEntity
    {

        [ForeignKey("StatusProjeto")]
        public long IdStatusProjeto { get; set; }
        public virtual ConteudoTabelaDominio StatusProjeto { get; set; }
       
        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        public string TxtJustificativa { get; set; }
    }
}
