//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using Agnus.Domain.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoRegistro")]
    public partial class ProjetoRegistro : KeyAuditableEntity, ILogProjeto
    {
        public ProjetoRegistro()
        {
            ProjetoCaptacaos = new HashSet<ProjetoCaptacao>();
        }

        //public long Id { get; set; }
        //public string IdRegistro { get; set; }
        public DateTime DataAberturaProcesso { get; set; }
        public DateTime DataAprovacao { get; set; }
        public DateTime? DataRenovacao { get; set; }
        public DateTime DataValidade { get; set; }
        public DateTime? DataDescontinuidade { get; set; }
        public string NumRegistro { get; set; }
        //public string IndHibrido { get; set; }

        [ForeignKey("TipoRegistro")]
        public long IdTipoRegistro { get; set; }
        public virtual ConteudoTabelaDominio TipoRegistro { get; set; }

        [ForeignKey("PessoaOrgaoRegulador")]
        public long IdPessoaOrgaoRegulador { get; set; }
        public virtual Pessoa PessoaOrgaoRegulador { get; set; }

        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        [ForeignKey("IncentivoFiscal")]
        public long IdIncentivoFiscal { get; set; }
        public virtual IncentivoFiscal IncentivoFiscal { get; set; }

        [NotMapped]
        public string Nome { get { return PessoaOrgaoRegulador != null ? PessoaOrgaoRegulador.NomePessoa : string.Empty; } }

        public virtual ICollection<ProjetoCaptacao> ProjetoCaptacaos { get; set; }

        [NotMapped]
        public string NomeEntidade
        {
            get { return "Registro"; }
        }
    }
}
