//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoPremio")]
    public partial class ProjetoPremio : KeyAuditableEntity, ILogProjeto
    {
        //public long Id { get; set; }
        //public string IdPremio { get; set; }
        public DateTime dataPremio { get; set; }
        public decimal ValPremio { get; set; }

        [ForeignKey("CategoriaPremio")]
        public long? IdCategoriaPremio { get; set; }
        public virtual CategoriaPremio CategoriaPremio { get; set; }

        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        [ForeignKey("TipoPremio")]
        public long IdTipoPremio { get; set; }
        public virtual TipoPremio TipoPremio { get; set; }

        [NotMapped]
        public string NomeEntidade
        {
            get { return "Premio"; }
        }
    }
}
