//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using Agnus.Domain.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoAudiencia")]
    public partial class ProjetoAudiencia : KeyAuditableEntity, ILogProjeto
    {
        //public long Id { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime? DataFim { get; set; }
        public decimal ValorBruto { get; set; }
        public string NumAudiencia { get; set; }

        [ForeignKey("TipoAudiencia")]
        public long IdTipoAudiencia { get; set; }
        public virtual ConteudoTabelaDominio TipoAudiencia { get; set; }

        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        [NotMapped]
        public string NomeEntidade
        {
            get { return "Audiencia"; }
        }
    }
}
