//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using Agnus.Domain.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoCaptacao")]
    public partial class ProjetoCaptacao : KeyAuditableEntity, ILogProjeto
    {
        //public long Id { get; set; }
        //public string IdCaptacao { get; set; }
        public decimal ValPercentualCaptacao { get; set; }
        public decimal ValCaptacao { get; set; }
        public DateTime DataCaptacao { get; set; }
        public DateTime DataPrevisaoRecebimento { get; set; }
        public string TxtObservacao { get; set; }

        [ForeignKey("TipoInvestimento")]
        public long IdTipoInvestimento { get; set; }
        public virtual ConteudoTabelaDominio TipoInvestimento { get; set; }

        [ForeignKey("IncentivoFiscal")]
        public long? IdIncentivoFiscal { get; set; }
        public virtual IncentivoFiscal IncentivoFiscal { get; set; }

        [ForeignKey("PessoaInvestidor")]
        public long IdPessoaInvestidor { get; set; }
        public virtual Pessoa PessoaInvestidor { get; set; }

        [ForeignKey("PessoaCaptador")]
        public long IdPessoaCaptador { get; set; }
        public virtual Pessoa PessoaCaptador { get; set; }

        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        [ForeignKey("ProjetoRegistro")]
        public long? IdProjetoRegistro { get; set; }
        public virtual ProjetoRegistro ProjetoRegistro { get; set; }

        [NotMapped]
        public string NomeEntidade
        {
            get { return "Captacao"; }
        }
    }
}
