//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoHistoricoTitulo")]
    public partial class ProjetoHistoricoTitulo : KeyAuditableEntity
    {
        //public long Id { get; set; }
        public string TxtTitulo { get; set; }
        public DateTime? DataCadastro { get; set; }

        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }
    }
}
