//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ProjetoRoteiro")]
    public partial class ProjetoRoteiro : KeyAuditableEntity, ILogProjeto
    {
        //public long Id { get; set; }
        //public string IdRoteiro { get; set; }
        public DateTime DataRecebimento { get; set; }
        public string TxtRoteiro { get; set; }
        public bool IndMinc { get; set; }
        public bool IndBiblioteca { get; set; }

        [ForeignKey("PessoaRoteirista")]
        public long? IdPessoaRoteirista { get; set; }
        public virtual Pessoa PessoaRoteirista { get; set; }

        [ForeignKey("Projeto")]
        public long IdProjeto { get; set; }
        public virtual Projeto Projeto { get; set; }

        [NotMapped]
        public string NomeEntidade
        {
            get { return "Roteiro"; }
        }
    }
}
