//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TipoPremio")]
    public partial class TipoPremio : KeyAuditableEntity
    {
        public TipoPremio()
        {
            this.CategoriaPremio = new HashSet<CategoriaPremio>();
            this.ProjetoPremio = new HashSet<ProjetoPremio>();
        }

        [Index("IX_Codigo_IX", IsUnique = true)]
        public long Codigo { get; set; }
        //public string IdTipoPremio { get; set; }
        public string TxtTipoPremio { get; set; }
        public bool IndAtivo { get; set; }
    

        [ForeignKey("PessoaOutorgante")]
        public long? IdPessoaOutorgante { get; set; }
        public virtual Pessoa PessoaOutorgante { get; set; }

        public virtual ICollection<ProjetoPremio> ProjetoPremio { get; set; }
    }
}
