//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("WorkflowSubstituto")]
    public partial class WorkflowSubstituto : KeyAuditableEntity
    {
        [ForeignKey("PessoaTitular")]
        public long IdPessoaTitular { get; set; }
        public virtual Pessoa PessoaTitular { get; set; }

        [ForeignKey("PessoaSubstituto")]
        public long IdPessoaSubstituto { get; set; }
        public virtual Pessoa PessoaSubstituto { get; set; }

        [ForeignKey("ObjetoAprovacao")]
        public long? IdObjetoAprovacao { get; set; }
        public virtual ConteudoTabelaDominio ObjetoAprovacao { get; set; }

        public bool IndAtivo { get; set; }
    }
}
