using Agnus.Domain.Models;
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Domain;
    using Agnus.Domain.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("WorkflowAprovacao")]
    public partial class WorkflowAprovacao : KeyAuditableEntity
    {
        public WorkflowAprovacao()
        {
            this.WorkflowParecer = new HashSet<WorkflowParecer>();
            this.WorkFlow = new HashSet<WorkFlow>();
        }

        public int NumNivel { get; set; }
        public int? ValorSLAHora { get; set; }
        public decimal? ValorAlcada { get; set; }
        public bool IndAtivo { get; set; }

        [ForeignKey("Pessoa")]
        public long? IdPessoaAprovador { get; set; }
        public virtual Pessoa Pessoa { get; set; }

        [ForeignKey("PapelAprovador")]
        public long? IdPapelAprovador { get; set; }
        public virtual ConteudoTabelaDominio PapelAprovador { get; set; }

        [ForeignKey("ObjetoAprovacao")]
        public long IdObjetoAprovacao { get; set; }
        public virtual ConteudoTabelaDominio ObjetoAprovacao { get; set; }

        public virtual ICollection<WorkflowParecer> WorkflowParecer { get; set; }
        public virtual ICollection<WorkFlow> WorkFlow { get; set; }
    }
}
