//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("AgrupamentoItemConta")]
    public partial class AgrupamentoItemConta : KeyAuditableEntity
    {
        public AgrupamentoItemConta()
        {
            this.ItemPlanoContas = new HashSet<ItemPlanoContas>();
        }

        public string Nome { get; set; }
        public bool IndAtivo { get; set; }
        
        public virtual ICollection<ItemPlanoContas> ItemPlanoContas { get; set; }
    }
}
