//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

    [Table("BibliotecaItem")]
    public partial class BibliotecaItem : KeyAuditableEntity
    {
        [Required]
        public string Sigla { get; set; }

        public string Descricao { get; set; }

        public decimal Valor { get; set; }

        public string Formula { get; set; }
        
        [ForeignKey("Biblioteca")]
        public long IdBiblioteca { get; set; }
        public Biblioteca Biblioteca { get; set; }
    }
}
