//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Biblioteca")]
    public partial class Biblioteca : KeyAuditableEntity
    {
        public Biblioteca()
        {
            this.BibliotecaItems = new HashSet<BibliotecaItem>();
        }

        public string Nome { get; set; }

        public bool IndDefault { get; set; }

        public bool IndInativo { get; set; }

        [ForeignKey("Nucleo")]
        public long IdNucleo { get; set; }
        public virtual Nucleo Nucleo { get; set; }

        [ForeignKey("TipoBiblioteca")]
        public long IdTipoBiblioteca { get; set; }
        public virtual ConteudoTabelaDominio TipoBiblioteca { get; set; }

        public virtual ICollection<BibliotecaItem> BibliotecaItems { get; set; }
    }
}
