//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("ItemPlanoContas")]
    public partial class ItemPlanoContas : KeyAuditableEntity
    {
        public ItemPlanoContas()
        {
            this.ItemOrcamento = new HashSet<ItemOrcamento>();
            this.OrcamentoTotal = new HashSet<OrcamentoTotal>();

            TipoMaterials = new HashSet<TipoMaterial>();
            TipoServicoes = new HashSet<TipoServico>();
        }

        public string TxtItemPlanoContas { get; set; }

        public string CodItemPlanoContas { get; set; }

        public bool IndAtivo { get; set; }
        public string TxtFormulaCalculo { get; set; }

        [ForeignKey("PlanoContasGrupo")]
        public long? IdPlanoContasGrupo { get; set; }
        public PlanoContasGrupo PlanoContasGrupo { get; set; }

        [ForeignKey("AgrupamentoItemConta")]
        public long? IdAgrupamentoItemConta { get; set; }
        public ConteudoTabelaDominio AgrupamentoItemConta { get; set; }

        public virtual ICollection<ItemOrcamento> ItemOrcamento { get; set; }
        public virtual ICollection<OrcamentoTotal> OrcamentoTotal { get; set; }

        public virtual ICollection<TipoMaterial> TipoMaterials { get; set; }

        public virtual ICollection<TipoServico> TipoServicoes { get; set; }
    }
}
