//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrcamentoPeriodo")]
    public partial class OrcamentoPeriodo : KeyAuditableEntity
    {
        public int NumAno { get; set; }
        public int NumMes { get; set; }
        public decimal ValorItem { get; set; }
        public DateTime DataInicio { get; set; }
        public DateTime DataFim { get; set; }
        public decimal? Percentual { get; set; }

        [ForeignKey("OrcamentoTotal")]
        public long IdOrcamentoTotal { get; set; }
        public virtual OrcamentoTotal OrcamentoTotal { get; set; }
    }
}
