//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrcamentoRealUso")]
    public partial class OrcamentoRealUso : KeyAuditableEntity
    {
        public decimal ValorUso { get; set; }
        public long IdCodObjetoUso { get; set; }
        public long IdObjetoUso { get; set; }

        [ForeignKey("OrcamentoAtual")]
        public long IdOrcamentoAtual { get; set; }
        public virtual OrcamentoAtual OrcamentoAtual { get; set; }
    }
}
