//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrcamentoAtual")]
    public partial class OrcamentoAtual : KeyAuditableEntity
    {
        public OrcamentoAtual()
        {
            this.OrcamentoProdutorUso = new HashSet<OrcamentoProdutorUso>();
            this.OrcamentoRealUso = new HashSet<OrcamentoRealUso>();
        }
    
        
        public int? NumAno { get; set; }
        public int? NumMes { get; set; }
        public DateTime? DataInicio { get; set; }
        public DateTime? DataFim { get; set; }
        public decimal ValorItemReal { get; set; }
        public decimal ValorItemProdutor { get; set; }
        public decimal ValorUsoReal { get; set; }
        public decimal ValorUsoProdutor { get; set; }        

        [ForeignKey("ItemOrcamento")]
        public long IdItemOrcamento { get; set; }
        public virtual ItemOrcamento ItemOrcamento { get; set; }

        [ForeignKey("ProjetoOrcamento")]
        public long IdProjetoOrcamento { get; set; }
        public virtual ProjetoOrcamento ProjetoOrcamento { get; set; }

        public virtual ICollection<OrcamentoProdutorUso> OrcamentoProdutorUso { get; set; }
        public virtual ICollection<OrcamentoRealUso> OrcamentoRealUso { get; set; }

        [NotMapped]
        public string NomeFase { get { return this.ItemOrcamento.NomeFase; } }
        [NotMapped]
        public string NomeEtapa { get { return this.ItemOrcamento.NomeEtapa; } }
        [NotMapped]
        public string CodGrupo { get { return this.ItemOrcamento.CodGrupo; } }
        [NotMapped]
        public string NomeGrupo { get { return this.ItemOrcamento.NomeGrupo; } }
        [NotMapped]
        public string CodItem { get { return this.ItemOrcamento.CodItem; } }
        [NotMapped]
        public string NomeItem { get { return this.ItemOrcamento.NomeItem; } }
        [NotMapped]
        public decimal ValorTotal { get { return this.ValorItemReal; } }
        
    }
}
