//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("OrcamentoProdutorUso")]
    public partial class OrcamentoProdutorUso : KeyAuditableEntity
    {
        public decimal ValorUso { get; set; }

        public long CodObjetoUso { get; set; }

        public long NumIdObjetoUso { get; set; }

        [ForeignKey("ObjetoComprometimentoOrcamento")]
        public long? IdObjetoOrcamento { get; set; }
        public virtual ConteudoTabelaDominio ObjetoComprometimentoOrcamento { get; set; }

        [ForeignKey("OrcamentoAtual")]
        public long IdOrcamentoAtual { get; set; }
        public virtual OrcamentoAtual OrcamentoAtual { get; set; }

    }
}
