//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agnus.Domain.Models
{
    using Agnus.Framework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

    [Table("PlanoContas")]
    public partial class PlanoContas : Entity
    {
        public PlanoContas()
        {
            this.PlanoContasGrupos = new HashSet<PlanoContasGrupo>();
        }

        [Required]
        public string Nome { get; set; }

        public bool IndAtivo { get; set; }

        public virtual ICollection<PlanoContasGrupo> PlanoContasGrupos { get; set; }
    }
}
